# Site settings
title: Jad Moawad
description: Academic Website
baseurl: ""
url: "https://jadmoawad.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Default layout settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"