# Site settings
title: "Jad Moawad"
description: "Postdoctoral Researcher at Oxford"
author: "Jad Moawad"
baseurl: ""
url: "https://jadmoawad.github.io"

# Build settings
markdown: kramdown
permalink: pretty  # This gives cleaner URLs without .html

# Navigation (simplified since we're handling nav in the layout)
header_pages:
  - index.md
  - research.md
  - teaching.md

# Plugins
plugins:
  - jekyll-seo-tag  # Keep this for better SEO
  
# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt
