title: "Jad Moawad"
description: "Postdoctoral Researcher at Oxford"
author: "Jad Moawad"
baseurl: ""
url: "https://jadmoawad.github.io"

# Build settings
markdown: kramdown
permalink: /:title/

# Navigation
header_pages:
  - index.md
  - research.md
  - teaching.md

# Theme settings
remote_theme: chesterhow/tale
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/gems/
  - vendor/ruby/
